### PR TITLE
Some refactoring, tests, doc blocks

### PR DESCRIPTION
**Pull request by splitbrain**
This refactors the library into separate files per class as suggested by @tm1000 in #18. It also introduces  unit testing with some initial tests. More tests at a deeper level would make sense though (currently it just checks the overall outcome). I also added doc blocks to make things bit easier to understand and for better type hinting in IDEs. This also incorporates #23. After merging, automated unit testing at travis-ci should be set up.

If you're not interested in this, feel free to close.

### CODE REVIEW

**Comment by tm1000** [comment]
This is really impressive and should be merged. 👍 

One note: Does this require a major version bump? I suppose not. It looks like it's backwards compatible.

**Comment by skrivy** [comment]
Would you mind merging this?

**Comment by Humni** [comment]
This should be merged. Is this repo managed still?

**Comment by analogic** [comment]
I appreciate this pull request but it is far from the original purpose of Lescript - to be a simple single file without deps.

**Pull request closed without merging**
