### PR TITLE
Make HTTP client exchangable

### PR DESCRIPTION
**Pull request by splitbrain**
This introduces an Interface that defines what a suitable HTTPClient needs to provide and makes it possible to pass an alternative implementation in the Lescript constructor.

PS: I can provide another PullRequest introducing doc blocks to all other methods if you're interested. DocBlocks make working with a library much easier IMHO. just let me know.

### CODE REVIEW

**Comment by maxnet** [comment]
Was wondering why there needs to be a dependency on curl or some other HTTP client in the first place.
Not possible to just use the standard PHP https stream wrapper?

**Comment by tm1000** [comment]
At this point the project should probably have separate files for each interface/class/etc. Makes organization much easier.

**Comment by splitbrain** [comment]
I am happy to split it up into multiple files if that's what is wanted.

**Comment by analogic** [comment]
@maxnet you are right!

**Comment by splitbrain** [comment]
Uhm thanks for incorporating my changes. Though a true merge (and thus giving proper credit in the commit history) would have been the decent thing to do.

**Pull request closed without merging**
