### PR TITLE
ACME Asynchronous Order Finalization compatibility

### LINKED ISSUE #43: Breaks with LE Asynchronous Order Finalization
LE is activating Asynchronous Order Finalization (https://community.letsencrypt.org/t/enabling-asynchronous-order-finalization/193522) which breaks lescript ...
Not sure if someone is still using lescript as it's dead for years by now ... but if wanted I can publish a PR to make it compatible with breaking Asynchronous Order Finalization changes ...

### PR DESCRIPTION
**Pull request by futureweb**
Adds compatibility with ACME protocol for Asynchronous Order Finalization.
Reference: https://community.letsencrypt.org/t/breaking-changes-in-asynchronous-order-finalization-api/195882

Fixes: https://github.com/analogic/lescript/issues/43

### CODE REVIEW

**Comment by analogic** [comment]
LGTM

**Comment by liljefelt** [comment]
Hi guys, where is $orderStatusUrl set?
I see the variable used twice, but it is not set anywhere.

**Comment by futureweb** [comment]
@liljefelt - I'm using a heavily customized version of lescript in my env. and overlooked that $orderStatusUrl isn't available in the original script.
Plese replace all occurances of $orderStatusUrl with $this->client->getLastLocation() and it should work as expected - I will make a PR for this shortly.

**Comment by liljefelt** [comment]
> @liljefelt - I'm using a heavily customized version of lescript in my env. and overlooked that $orderStatusUrl isn't available in the original script. Plese replace all occurances of $orderStatusUrl with $this->client->getLastLocation() and it should work as expected - I will make a PR for this shortly.

Thank you very much for the quick response.
I have a bunch of hobby servers using this script, also somewhat modified, and I'm very thankful for this update!

**Pull request merged**
